### PR TITLE
Add subnet registry

### PR DESCRIPTION
**Pull request by cryptoAtwill**
Support subnet actor registry that deploys subnet contract from registry contract. At the same time, it also tracks the deployed subnet onchain.

### CODE REVIEW

**Review by adlrocha — APPROVED** [review]

**Review by adlrocha — CHANGES_REQUESTED** [review]
@cryptoAtwill, can we add a deployment scripts for the registry in `scripts/`, please? So we have all the scripts to deploy the IPC suite.

**Review by mikirov — CHANGES_REQUESTED** [review]
We had a call with Alfonso, let's have a hardhat deployment script for the registry as well

**Review by arrusev — CHANGES_REQUESTED** [review]
Since the `SubnetRegistry` and `Gateway` will be deployed by the same trusted actor, maybe it would be good if the `SubnetRegistry` has a constructor that accepts the address of the gateway, so deploying the subnet not relying on an externally passed gateway address.

**Review by adlrocha — DISMISSED** [review]
@arrusev, @mikirov are we ok merging this one? Thanks!

**Review by mikirov — DISMISSED** [review]

**Review by arrusev — APPROVED** [review]
LGTM.

**Comment by adlrocha** [comment]
@arrusev, @mikirov, do you mind merging this one if it LGTY? I don´t  seem to have permissions :pray:

**Review by mikirov — APPROVED** [review]

**Pull request merged**
